services:
  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped
    depends_on:
      - frontend
      - backend

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: unless-stopped
    env_file:
    - ./backend/.env
    command: >
      dockerize -wait tcp://db:3306 -timeout 60s 
      uvicorn main:app --host 0.0.0.0 --port 8000
    image : violalag/audio-spoof-cnn:backend-latest



  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: react_frontend
    restart : always
    ports:
      - "3000:3000"  
    env_file:
      - ./frontend/.env.production
    depends_on:
      - backend
    image : violalag/audio-spoof-cnn:frontend-latest

volumes:
  db_data:
  caddy_data:
  caddy_config:
  


