"""Initial schema

Revision ID: 8e13e189f78b
Revises: 
Create Date: 2025-06-08 19:28:38.752005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8e13e189f78b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AudioInteraction',
    sa.Column('interaction_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('audio_file', sa.String(length=255), nullable=False),
    sa.Column('audio_format', sa.String(length=50), nullable=True),
    sa.Column('audio_duration', sa.Float(), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=True),
    sa.Column('time_created', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('interaction_id')
    )
    op.create_index(op.f('ix_AudioInteraction_interaction_id'), 'AudioInteraction', ['interaction_id'], unique=False)
    op.create_index(op.f('ix_AudioInteraction_session_id'), 'AudioInteraction', ['session_id'], unique=False)
    op.create_table('DetectionResult',
    sa.Column('result_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('is_spoof', sa.Boolean(), nullable=True),
    sa.Column('metric_score', sa.Float(), nullable=True),
    sa.Column('model_use', sa.String(length=50), nullable=False),
    sa.Column('image_filename', sa.String(length=255), nullable=True),
    sa.Column('time_detect', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['AudioInteraction.session_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('result_id')
    )
    op.create_index(op.f('ix_DetectionResult_result_id'), 'DetectionResult', ['result_id'], unique=False)
    op.create_table('UserFeedback',
    sa.Column('feedback_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('result_id', sa.Integer(), nullable=False),
    sa.Column('feedback', sa.Boolean(), nullable=True),
    sa.Column('time_submit', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['result_id'], ['DetectionResult.result_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('feedback_id')
    )
    op.create_index(op.f('ix_UserFeedback_feedback_id'), 'UserFeedback', ['feedback_id'], unique=False)
    op.drop_table('detectionresult')
    op.drop_table('userfeedback')
    op.drop_table('audiointeraction')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audiointeraction',
    sa.Column('interaction_id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('session_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('audio_file', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('audio_format', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('audio_duration', mysql.FLOAT(), nullable=True),
    sa.Column('source_type', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('time_created', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('interaction_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('userfeedback',
    sa.Column('feedback_id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('result_id', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('feedback', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('time_submit', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['result_id'], ['detectionresult.result_id'], name=op.f('userfeedback_ibfk_1'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('feedback_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('detectionresult',
    sa.Column('result_id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('interaction_id', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('is_spoof', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('metric_score', mysql.FLOAT(), nullable=True),
    sa.Column('model_use', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('time_detect', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['interaction_id'], ['audiointeraction.interaction_id'], name=op.f('detectionresult_ibfk_1'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('result_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_index(op.f('ix_UserFeedback_feedback_id'), table_name='UserFeedback')
    op.drop_table('UserFeedback')
    op.drop_index(op.f('ix_DetectionResult_result_id'), table_name='DetectionResult')
    op.drop_table('DetectionResult')
    op.drop_index(op.f('ix_AudioInteraction_session_id'), table_name='AudioInteraction')
    op.drop_index(op.f('ix_AudioInteraction_interaction_id'), table_name='AudioInteraction')
    op.drop_table('AudioInteraction')
    # ### end Alembic commands ###
